POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer {koodi tähän, esim loginin jälkeen nähtävä}

{
    "title": "Murinoja Mahassa",
    "author": "Matti Murkina",
    "url": "www.murinaamahassaa.fi",
    "likes": "70"
}